version: '2.1'
services:
    db:
        image: sameersbn/postgresql:9.6-2
        container_name: gitlab-postgresql
        restart: always
        volumes:
            - /srv/docker/gitlab/postgresql:/var/lib/postgresql
        environment:
            - DB_NAME=gitlabhq_production
            - DB_USER=gitlab
            - DB_PASS=password
            - DB_EXTENSION=pg_trgm
        env_file:
            - /var/opt/gitlab/.env
    redis:
        image: sameersbn/redis:latest
        container_name: gitlab-redis
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/docker/gitlab/redis:/var/lib/redis
        environment:
            - REDIS_USER=redis
            - REDIS_DATA_DIR=/var/lib/redis
            - REDIS_LOG_DIR=/var/log/redis
    gitlab:
        image: sameersbn/gitlab:latest
        container_name: gitlab
        links:
            - db
            - redis
        volumes:
            - /var/opt/gitlab/backups:/home/git/data/backups
            - /srv/docker/gitlab/gitlab:/home/git/data
            - /var/opt/gitlab/env:/home/git/env
            - /etc/localtime:/etc/localtime:ro
            - /srv/docker/gitlab/redis:/var/lib/redis
        ports:
            - "443:443"
            - "10022:22"
        env_file:
            - /var/opt/gitlab/.env
    redmine:
        image: sameersbn/redmine:3.4.4-2
        depends_on:
            - db
              
   
